# Generated by Django 2.0.6 on 2018-06-13 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leaders',
            field=models.ManyToManyField(related_name='leader_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
