# Generated by Django 2.0.6 on 2018-06-13 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180613_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hearters',
            field=models.ManyToManyField(blank=True, related_name='hearted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hearted_users',
            field=models.ManyToManyField(blank=True, related_name='_user_hearted_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
