# Generated by Django 2.0.6 on 2018-06-13 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180613_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearted_users',
            field=models.ManyToManyField(blank=True, related_name='hearted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
