# Generated by Django 2.0.6 on 2018-06-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180613_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hearters',
            new_name='hearted_by',
        ),
    ]
