# Generated by Django 2.0.6 on 2018-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='projectjoinrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
