# Generated by Django 2.0.6 on 2018-06-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180613_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectjoinrequest',
            options={'verbose_name': 'Project Join Request', 'verbose_name_plural': 'Project Join Requests'},
        ),
    ]
