# Generated by Django 2.0.6 on 2018-06-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180613_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Project')),
            ],
            options={
                'verbose_name': 'Project Post',
                'verbose_name_plural': 'Project Posts',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'verbose_name': 'Project Comment', 'verbose_name_plural': 'Project Comments'},
        ),
    ]
