# Generated by Django 2.0.6 on 2018-06-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180613_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
