# Generated by Django 2.0.6 on 2018-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180614_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
