# Generated by Django 2.0.6 on 2018-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180614_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
