# Generated by Django 2.0.6 on 2018-06-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_projectjoinrequest_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='private',
        ),
    ]
