# Generated by Django 2.0.6 on 2018-06-14 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180614_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hearted_by',
            field=models.ManyToManyField(blank=True, related_name='hearted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
