# Generated by Django 2.0.6 on 2018-06-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180614_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearts',
            field=models.IntegerField(default=0, help_text='Yu Yu'),
        ),
    ]
