# Generated by Django 2.0.7 on 2018-07-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180719_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersiterole',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='site_roles',
            field=models.ManyToManyField(related_name='users', to='api.UserSiteRole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
