# Generated by Django 2.0.7 on 2018-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180719_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='taken_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_count',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.UserSiteRole'),
        ),
    ]
