"""empty message

Revision ID: 2926750f49a0
Revises: fad1efa972e7
Create Date: 2018-03-20 15:12:55.843252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2926750f49a0'
down_revision = 'fad1efa972e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('project', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'project', ['project'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'project')
    # ### end Alembic commands ###
