"""empty message

Revision ID: 2a9a7b008855
Revises: a266bb11ee45
Create Date: 2018-03-20 15:29:33.367074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a9a7b008855'
down_revision = 'a266bb11ee45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('comment', 'created')
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('post', 'created')
    op.add_column('project', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('project', 'created')
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('user', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'timestamp')
    op.add_column('project', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('project', 'timestamp')
    op.add_column('post', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('post', 'timestamp')
    op.add_column('comment', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'timestamp')
    # ### end Alembic commands ###
