"""empty message

Revision ID: 47ba8066f852
Revises: bf682c77f4e4
Create Date: 2018-03-20 15:04:48.259588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ba8066f852'
down_revision = 'bf682c77f4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_project_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_user_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'project')
    op.drop_column('comment', 'user')
    op.drop_constraint('post_project_fkey', 'post', type_='foreignkey')
    op.drop_constraint('post_user_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'project')
    op.drop_column('post', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('post_user_fkey', 'post', 'user', ['user'], ['id'])
    op.create_foreign_key('post_project_fkey', 'post', 'project', ['project'], ['id'])
    op.add_column('comment', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comment_user_fkey', 'comment', 'user', ['user'], ['id'])
    op.create_foreign_key('comment_project_fkey', 'comment', 'project', ['project'], ['id'])
    # ### end Alembic commands ###
