"""empty message

Revision ID: a266bb11ee45
Revises: 12dcf33df8e9
Create Date: 2018-03-20 15:24:56.497274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a266bb11ee45'
down_revision = '12dcf33df8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_user_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_project_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'project', ['project_id'], ['id'])
    op.drop_column('comment', 'project')
    op.drop_column('comment', 'user')
    op.add_column('post', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_project_fkey', 'post', type_='foreignkey')
    op.drop_constraint('post_user_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'project')
    op.drop_column('post', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_fkey', 'post', 'user', ['user'], ['id'])
    op.create_foreign_key('post_project_fkey', 'post', 'project', ['project'], ['id'])
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'project_id')
    op.add_column('comment', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_project_fkey', 'comment', 'project', ['project'], ['id'])
    op.create_foreign_key('comment_user_fkey', 'comment', 'user', ['user'], ['id'])
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'project_id')
    # ### end Alembic commands ###
