"""empty message

Revision ID: a42c3f7c4a8d
Revises: f3442e72997c
Create Date: 2018-06-04 09:44:25.486792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42c3f7c4a8d'
down_revision = 'f3442e72997c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('about', sa.String(), nullable=True))
    op.drop_column('project', 'description')
    op.add_column('user', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about')
    op.add_column('project', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project', 'about')
    # ### end Alembic commands ###
