"""empty message

Revision ID: fad1efa972e7
Revises: 47ba8066f852
Create Date: 2018-03-20 15:10:30.603710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad1efa972e7'
down_revision = '47ba8066f852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user')
    # ### end Alembic commands ###
